apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-wtsukx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-wtsukx
    app.kubernetes.io/part-of: jvm-build-suite-application-hloe
  name: jvm-build-suite-component-wtsukx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-wtsukx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-wtsukx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-hpje-tenant/jvm-build-suite-application-hloe/jvm-build-suite-component-wtsukx@sha256:7c83768386e11f95b9c011536767dfd9345948e881dad93e050b32e7bf90b747
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
